name: Docs Server CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login
        env:
          GITHUB_TOKEN: ${{ secrets.WHATEVER }}
        run:  docker login ghcr.io --username phanatic --password "$GITHUB_TOKEN"
      - name: Build & Tag
        run:  docker build -t ghcr.io/bankobotv14/docdexdocker:latest -t ghcr.io/bankobotv14/docdexdocker:"$GITHUB_SHA" .
      - name: Push
        run:  docker push ghcr.io/bankobotv14/docdexdocker:latest ghcr.io/bankobotv14/docdexdocker:"$GITHUB_SHA"
       
      